
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdvrfvymnvxyfozavcwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkdnJmdnltbnZ4eWZvemF2Y3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzYzMDgsImV4cCI6MjA1Njk1MjMwOH0.1wk22FwW8h8Tr2AdZwz9F3pPJIBzgQ-hM-xic-OtcdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
